Jump Token 구현
DesignPatternCAU/rabbit-escape pull request #3
Opened 2024-12-04 10:16 UTC by firekann

Jump Token 구현 + 테스트
애니메이션과 토큰 이미지는 미흡할 수 있음.

2024-12-04 13:34 UTC, boulce requested changes

2024-12-04 13:34 UTC, boulce commented on src/engine/src/rabbitescape/engine/behaviours/Jumping.java
> +            if (t.isOnDownSlope()) return t.rl(RABBIT_JUMPING_ON_DOWN_SLOPE_RIGHT, RABBIT_JUMPING_ON_DOWN_SLOPE_LEFT);
여기도 if(t.blockBelowNext() != null || t.blockBelow2Next() != null) return null; 이런식으로 추가해야하는 것 아닌가?

2024-12-04 13:34 UTC, boulce commented on src/engine/src/rabbitescape/engine/textworld/ChangeRenderer.java
> +            case RABBIT_JUMPING_ON_DOWN_SLOPE_LEFT:
chars.set( change.x, change.y + 1, 'w' ); 해야하는 것 아닌가?

2024-12-04 13:34 UTC, boulce commented on src/engine/src/rabbitescape/engine/textworld/ChangeRenderer.java
> +            case RABBIT_JUMPING_ON_DOWN_SLOPE_RIGHT:
chars.set( change.x, change.y + 1, 'w' ); 해야하는 것 아닌가?

2024-12-04 13:34 UTC, boulce commented on src/engine/src/rabbitescape/levels/01_easy/01_Digging-practice.rel
>  ###########
:jump=5
:dig=5
###########
#             Q     #
#\                 /##
###########
#                    #
#\                O#
####### ###

이런식으로 jump를 쓸 수 있는 **데모용** 맵을 추가해야할 것으로 보임

2024-12-04 15:57 UTC, firekann commented on src/engine/src/rabbitescape/levels/01_easy/01_Digging-practice.rel
>  ###########
이건 나중에 논의해서 한 번에 만들기로 했음.

2024-12-04 15:59 UTC, firekann commented on src/engine/src/rabbitescape/engine/textworld/ChangeRenderer.java
> +            case RABBIT_JUMPING_ON_DOWN_SLOPE_LEFT:
ㄴㄴ 이게 맞음. 내려가는 건 이미 + 좌표임

2024-12-04 15:59 UTC, firekann commented on src/engine/src/rabbitescape/engine/textworld/ChangeRenderer.java
> +            case RABBIT_JUMPING_ON_DOWN_SLOPE_RIGHT:
ㄴㄴ 이게 맞음. 내려가는 건 이미 +1 한 좌표임

2024-12-04 16:02 UTC, firekann commented on src/engine/src/rabbitescape/engine/behaviours/Jumping.java
> +            if (t.isOnDownSlope()) return t.rl(RABBIT_JUMPING_ON_DOWN_SLOPE_RIGHT, RABBIT_JUMPING_ON_DOWN_SLOPE_LEFT);
아래 거랑 같은 맥락인데 UpSlope는 y 좌표가 -1하기 전이라 -1 좌표 쪽에 있는 걸 확인하는 거고, Down이랑 평지는 이미 점프할 y 좌표에 있어서 굳이 따로 검사할 필요가 없음. Token을 먹는 타이밍에 어떤 좌표에 있는지가 중요함.

2024-12-05 13:57 UTC, boulce approved these changes

2024-12-05 14:06 UTC, merged